/// Flutter icons PaymentOptions
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PaymentOptions
///      fonts:
///       - asset: fonts/PaymentOptions.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PaymentOptions {
  PaymentOptions._();

  static const _kFontFam = 'PaymentOptions';
  static const String _kFontPkg = null;
  static const IconData gcash =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paymaya =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pickup =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kpwallet =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
