/// Flutter icons RiderIconNavBar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RiderIconNavBar
///      fonts:
///       - asset: fonts/RiderIconNavBar.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RiderIconNavBar {
  RiderIconNavBar._();

  static const _kFontFam = 'RiderIconNavBar';
  static const String _kFontPkg = null;

  static const IconData history_icon_rider =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ongoing_icon_rider =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pickup_icon_rider_app =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scheduled_icon_rider_app =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
