name: kp_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  responsive_builder: ^0.4.1
  hexcolor: ^2.0.4
  flutter_speedometer: ^1.0.2
  speedometer: "^1.0.1"
  introduction_screen: ^2.1.0
  form_validator: ">=0.1.1 <2.0.0"
  tab_indicator_styler: ^1.0.0
  grouped_buttons: ^1.0.4
  timeline_tile: ^2.0.0
  provider: ^5.0.0
  google_maps_flutter: ^2.0.6
  google_maps_place_picker: ^2.0.0-nullsafety.3
  list_tile_switch: ^1.0.0
  pin_input_text_field: ^4.1.0
  pin_code_fields: ^7.2.0
  percent_indicator: ^3.0.1
  step_progress_indicator: ^1.0.1
  slider_button: ^1.0.0
  timelines: ^0.1.0
  flutter_dash: ^0.0.1
  flutter_rating_bar: ^4.0.0
  chips_choice: ^2.0.1
  json_annotation: ^4.0.1
  flutter_platform_widgets: ^1.9.5
  image_picker: ^0.8.1+3
  badges: ^2.0.1
  global_configuration: ^2.0.0-nullsafety.1
  fl_chart: ^0.40.0
  clipboard: ^0.1.2+8   
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.9
  share: ^2.0.0
  currency_text_input_formatter: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  numberpicker: ^2.0.1
  scroll_date_picker: ^2.0.1
  flutter_cupertino_datetime_picker: ^2.0.1
  timezone: ^0.7.0
  roundcheckbox: ^2.0.1
  flutter_google_places: ^0.3.0
  sizer: ^2.0.13
  responsive_sizer: ^3.0.4+4
  circular_countdown_timer: ^0.2.0
  open_file: ^3.2.1
  uuid: ^3.0.4
  flutter_chat_ui: ^1.1.5
  get_it: ^7.1.3
  android_intent_plus: ^1.0.2
  device_apps: ^2.1.1
  sms_autofill: ^2.0.0
  font_awesome_flutter: ^9.1.0
  another_flushbar: ^1.10.24
  dropdown_search: ^0.6.3
  syncfusion_flutter_charts: ^19.2.62

  
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  hive_generator: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/login_images/launcher_icon.jpg"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - messages.json
    - assets/login_images/KP_LOGO.png
    - assets/login_images/KP_profile.png
    - assets/otp_image/KP_OTP.jpg
    - assets/otp_image/KP_Icon2.png
    - assets/refer_a_Friend/KP_Refer.png
    - assets/payment_icons/pesoicon.png
    - assets/seller_Icons/Maginoo_icon.png
    - assets/cfg/
    - assets/drawer_icons/myaccount.png
    - assets/drawer_icons/mywallet.png
    - assets/drawer_icons/mybooking.png
    - assets/drawer_icons/dashboard_userSeller.png
    - assets/drawer_icons/helpcenter.png
    - assets/drawer_icons/mytoolbox.png
    - assets/drawer_icons/seller-Central.png
    - assets/drawer_icons/sellercentralicon.png
    - assets/drawer_icons/sellercentral3.png
    - assets/prohibited_items/1_insulatedbox.png
    - assets/prohibited_items/2_Drugs.png
    - assets/prohibited_items/3_Radioactive.png
    - assets/prohibited_items/4_Firearms.png
    - assets/prohibited_items/5_AnimalHumanRemains.png
    - assets/prohibited_items/6_LivingThings.png
    - assets/prohibited_items/7_CreditAtmCard.png
    - assets/prohibited_items/8_CashChecks.png
    - assets/prohibited_items/9_Flammable.png
    - assets/prohibited_items/10_PassportContract.png
    - assets/prohibited_items/11_ArchaeologicalArtifacts.png
    - assets/prohibited_items/12_Jerlweries.png
    - assets/flag_ph.png
    - assets/payment_icons/cod_abono.png
    - assets/payment_icons/gcash.png
    - assets/payment_icons/kpwallet2.png
    - assets/payment_icons/kpwallet3.png
    - assets/payment_icons/paymaya.png
    - assets/payment_icons/gcash_logo.png
    - assets/payment_icons/paymaya_logo.png
    - assets/pahatid_icons/reposition_icon.png
    - assets/pahatid_icons/cod_icon.png
    - assets/pahatid_icons/cop_icon.png
    - assets/payment_icons/kpwallet.png
    - assets/payment_icons/cod_eremit.png
    - assets/payment_icons/cod.png
    - assets/payment_icons/kpBox.png
    - assets/login_images/Zuck.jpg
    - assets/assigning_rider.png
    - assets/bg_chatwithus.png
    - assets/rider_icons/rider_arrived.png
    - assets/rider_icons/shopping_bag.png
    - assets/rider_icons/rider_dropoff_icon1.png
    - assets/rider_icons/rider_dropoff_icon2.png
    - assets/rider_icons/parcel_pickedup.png
    - assets/rider_icons/danger_sign.png
    - assets/rider_icons/rider_assigned.png
    - assets/pickup_address_icon/address_map_icon.png
    - assets/pickup_address_icon/address_popupbox_icon.png
    - assets/outside_service_area.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: fonts/HelveticaNeue-Regular.otf
    - family: Cocogoose
      fonts:
        - asset: fonts/CocogooseProSemilight-trial.ttf
    - family: UserDrawerIcons
      fonts:
        - asset: assets/drawer_Icon/fonts/UserDrawerIcons.ttf 
    - family: PaymentOptions
      fonts:
        - asset: assets/payment_icon/fonts/PaymentOptions.ttf     
    - family: RiderIconNavBar
      fonts:
        - asset: assets/RiderNavBarIcon/fonts/RiderIconNavBar.ttf    

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
